/*!
 * RedWarn - Recent Edits Patrol and Warning Tool
 * The user-friendly Wikipedia counter-vandalism tool.
 *
 * (c) 2020-2021 The RedWarn Development Team and contributors - tools.redwarn@toolforge.org or [[WT:RW]]
 * Licensed under the Apache License 2.0 - read more at https://www.apache.org/licenses/LICENSE-2.0.txt
 *
 * ------------------------------------------------------------------------------
 *
 * Copyright 2021 The RedWarn Development Team and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * ------------------------------------------------------------------------------
 *
 * RedWarn is an open source project, and we invite others to develop extensions,
 * styles, translation, and other expansions for RedWarn! If you'd like to learn
 * more, reach out at https://en.wikipedia.org/wiki/Wikipedia:RedWarn/Contact.
 *
 * ------------------------------------------------------------------------------
 *
 *               ! ATTENTION TO ALL WITH SCRIPT EDITING PERMISSIONS !
 *
 *             Changing this file will affect a large amount of users.
 *             It is not suggested that you directly change this file
 *              as there may be unknown implications of doing so. If
 *             there is an immediate threat posed by the script which
 *               needs to be settled immediately, please inform the
 *                     RedWarn team after making your changes.
 *
 *             This file is automatically generated by webpack when a
 *             new update is released. If you wish to modify the code,
 *              it is better to do so by making a pull request to the
 *              RedWarn repository on GitLab, which can be found here:
 *
 *                     https://gitlab.com/redwarn/redwarn-web/
 *
 * ------------------------------------------------------------------------------
 * Past this point, everything needs to be wrapped in a nowiki tag, or else we
 * risk "transcluding" templates.
 *
 * <nowiki>
 */
